name: Windows Build and Test

on:
  pull_request:

jobs:
    windows_debug:
      name: Windows Debug
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      runs-on: windows-2019
      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Configure project
          run: cmake -S . -B .build -DOPENGL_TESTS=OFF

        - name: Build project
          run: cmake --build .build --config Debug -j

        - name: Run tests
          run: cd .build; ctest --output-on-failure -C Debug

    #windows_release:
    #  name: Windows Release
    #  if: "!contains(github.event.head_commit.message, '[skip ci]')"
    #  runs-on: windows-2019
    #  steps:
    #    - name: Checkout sources
    #      uses: actions/checkout@v2

    #    - name: Configure project
    #      run: cmake -S . -B .build -DOPENGL_TESTS=OFF

    #    - name: Build project
    #      run: cmake --build .build --config Release -j

    #    - name: Run tests
    #      run: cd .build; ctest --output-on-failure -C Release
